### PR TITLE
Repository Overhaul

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**
  - `mod`
  - `raft`
  - `crafting`
  - `recipes`

  <br>

- **Update Description**

  `Raft mod making Cassettes craftable.`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>

<br>
<br>

## ![Badge Changes]

- Formatted README

- Added quicklink

- Added license badge

- Added mod icon

- Refactored code / manifest

  *please check if it works fine in your setup*

- Added missing license copy

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/raftmod_craftCassettes

### CODE REVIEW

**Comment by libkuza** [comment]
Hey Thank You, but it seems that something is wrong, can't load the mod in game. It caused a lot of errors.

**Comment by ElectronicsArchiver** [comment]
> please check if it works fine in your setup

What exactly is the problem if I might ask?

**Comment by libkuza** [comment]
Here are the caused errors while compiling.
[error_log.txt](https://github.com/libkuza/raftmod_craftCassettes/files/9223661/error_log.txt)

**Review by libkuza — DISMISSED** [review]

**Comment by ElectronicsArchiver** [comment]
Lemme fix them rly quick~

**Comment by ElectronicsArchiver** [comment]
Could you check again?

**Comment by libkuza** [comment]
[error_log.txt](https://github.com/libkuza/raftmod_craftCassettes/files/9223714/error_log.txt)

**Comment by ElectronicsArchiver** [comment]
Does your editor show you the 'add missing import / using option'
-> is the change correct?

**Comment by libkuza** [comment]
[error_log.txt](https://github.com/libkuza/raftmod_craftCassettes/files/9223737/error_log.txt)

**Comment by ElectronicsArchiver** [comment]
Considering I'm trying to fix this blackbox style, I'd rather revert the code refactor if you don't know how to fix the import~

Your decision

**Comment by libkuza** [comment]
There is no error with the import, there is just no definition for it because "addRange" must be "AddRange" and "toArray" must be "ToArray". I did that and then I haven't an error while compiling but there are some errors in the game then when he tries to add the Cassettes in to the research table.

**Comment by ElectronicsArchiver** [comment]
I activated 'Allow edits by maintainers' if you care to adjust it.

What errors occur in regards to the research table?

**Comment by libkuza** [comment]
[log.txt](https://github.com/libkuza/raftmod_craftCassettes/files/9227115/log.txt)
There were should be the paint to research is just a N/A . 
image

**Comment by ElectronicsArchiver** [comment]
I think I found the problem, let me fix it~

**Comment by ElectronicsArchiver** [comment]
Well one item name was wrong, the others look right though.

**Comment by ElectronicsArchiver** [comment]
@libkuza So, was that the only one with the problem?

**Comment by libkuza** [comment]
thank you, all problems are solved now

**Comment by ElectronicsArchiver** [comment]
Sorry for all the debugging~

**Pull request merged**
